### ISSUE TITLE
Parameterize executor via yaml/toml/json

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#955]
Been proposed several times. Tentative interface may resemble:

```
MPIExecutor:
   apps:
      forces: /path/to/forces
      learner: /path/to/another/app
   mpi_runner: "srun"
   subgroup_launch: false
```

Then the MPIExecutor as imported in the user function will have been initialized as expected, with apps registered
